/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root";
import { Route as RegisterRouteImport } from "./pages/register";
import { Route as LoginRouteImport } from "./pages/login";
import { Route as AboutRouteImport } from "./pages/about";
import { Route as IndexRouteImport } from "./pages/index";
import { Route as TodoIndexRouteImport } from "./pages/todo/index";
import { Route as TodoTodoIdRouteImport } from "./pages/todo/$todoId";

const RegisterRoute = RegisterRouteImport.update({
   id: "/register",
   path: "/register",
   getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
   id: "/login",
   path: "/login",
   getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
   id: "/about",
   path: "/about",
   getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
   id: "/",
   path: "/",
   getParentRoute: () => rootRouteImport,
} as any);
const TodoIndexRoute = TodoIndexRouteImport.update({
   id: "/todo/",
   path: "/todo/",
   getParentRoute: () => rootRouteImport,
} as any);
const TodoTodoIdRoute = TodoTodoIdRouteImport.update({
   id: "/todo/$todoId",
   path: "/todo/$todoId",
   getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
   "/": typeof IndexRoute;
   "/about": typeof AboutRoute;
   "/login": typeof LoginRoute;
   "/register": typeof RegisterRoute;
   "/todo/$todoId": typeof TodoTodoIdRoute;
   "/todo": typeof TodoIndexRoute;
}
export interface FileRoutesByTo {
   "/": typeof IndexRoute;
   "/about": typeof AboutRoute;
   "/login": typeof LoginRoute;
   "/register": typeof RegisterRoute;
   "/todo/$todoId": typeof TodoTodoIdRoute;
   "/todo": typeof TodoIndexRoute;
}
export interface FileRoutesById {
   __root__: typeof rootRouteImport;
   "/": typeof IndexRoute;
   "/about": typeof AboutRoute;
   "/login": typeof LoginRoute;
   "/register": typeof RegisterRoute;
   "/todo/$todoId": typeof TodoTodoIdRoute;
   "/todo/": typeof TodoIndexRoute;
}
export interface FileRouteTypes {
   fileRoutesByFullPath: FileRoutesByFullPath;
   fullPaths:
      | "/"
      | "/about"
      | "/login"
      | "/register"
      | "/todo/$todoId"
      | "/todo";
   fileRoutesByTo: FileRoutesByTo;
   to: "/" | "/about" | "/login" | "/register" | "/todo/$todoId" | "/todo";
   id:
      | "__root__"
      | "/"
      | "/about"
      | "/login"
      | "/register"
      | "/todo/$todoId"
      | "/todo/";
   fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
   IndexRoute: typeof IndexRoute;
   AboutRoute: typeof AboutRoute;
   LoginRoute: typeof LoginRoute;
   RegisterRoute: typeof RegisterRoute;
   TodoTodoIdRoute: typeof TodoTodoIdRoute;
   TodoIndexRoute: typeof TodoIndexRoute;
}

declare module "@tanstack/react-router" {
   interface FileRoutesByPath {
      "/register": {
         id: "/register";
         path: "/register";
         fullPath: "/register";
         preLoaderRoute: typeof RegisterRouteImport;
         parentRoute: typeof rootRouteImport;
      };
      "/login": {
         id: "/login";
         path: "/login";
         fullPath: "/login";
         preLoaderRoute: typeof LoginRouteImport;
         parentRoute: typeof rootRouteImport;
      };
      "/about": {
         id: "/about";
         path: "/about";
         fullPath: "/about";
         preLoaderRoute: typeof AboutRouteImport;
         parentRoute: typeof rootRouteImport;
      };
      "/": {
         id: "/";
         path: "/";
         fullPath: "/";
         preLoaderRoute: typeof IndexRouteImport;
         parentRoute: typeof rootRouteImport;
      };
      "/todo/": {
         id: "/todo/";
         path: "/todo";
         fullPath: "/todo";
         preLoaderRoute: typeof TodoIndexRouteImport;
         parentRoute: typeof rootRouteImport;
      };
      "/todo/$todoId": {
         id: "/todo/$todoId";
         path: "/todo/$todoId";
         fullPath: "/todo/$todoId";
         preLoaderRoute: typeof TodoTodoIdRouteImport;
         parentRoute: typeof rootRouteImport;
      };
   }
}

const rootRouteChildren: RootRouteChildren = {
   IndexRoute: IndexRoute,
   AboutRoute: AboutRoute,
   LoginRoute: LoginRoute,
   RegisterRoute: RegisterRoute,
   TodoTodoIdRoute: TodoTodoIdRoute,
   TodoIndexRoute: TodoIndexRoute,
};
export const routeTree = rootRouteImport
   ._addFileChildren(rootRouteChildren)
   ._addFileTypes<FileRouteTypes>();
